### ISSUE TITLE
Get offsetTop of added/removed item

### ISSUE THREAD

**Issue by NgKhanh** [joshwcomeau/react-flip-move#109]
Hi, I want to scroll to item which added/removed on listing. I using onStartAll(childElements, domNodes). but I dont know that first or last item of domNodes is added/removed, it is not fixed
```
const item= domNodes[0] //  or domNodes[domNodes.length-1] // 
scrollTo(item.offsetTop)
```
Any solution for this ? Thanks

**Comment by joshwcomeau** [comment]
Sorry for the delay, crazy busy this week.

So, internally FlipMove adds properties to the react elements to keep track of which ones are entering/leaving.

I would use `onStart` instead of `onStartAll`. You should be able to do something like this:

```js
moveToItemOnEnter(element, domNode) {
  if (element.entering) {
    scrollTo(domNode.offsetTop;
  }
}

// You can do the same thing for 'leaving'.
moveToItemOnLeave(element, domNode) {
  if (element.leaving) {
    scrollTo(domNode.offsetTop;
  }
}
```

This does depend on a non-public API so I can't guarantee that it won't change in the future. I would imagine such a change would be a major version anyway, though, since they're pretty fundamental right now.

Hope it helps!

**Comment by joshwcomeau** [comment]
actually, you may want to use `onEnterAll`/`onLeaveAll` anyway; if you have interrupted enters, the scroll position might jump around a ton.

`onEnterAll` waits for all animations to end, so you'd be guaranteed to only get 1 jump per set of animations. 

It's a bit more work (you have to zip the two arrays together to find the pairs of React Element and DOM Node), but it should be doable :)
