### ISSUE TITLE
Enter/Leave Animations

### ISSUE THREAD

**Issue by jbrantly** [joshwcomeau/react-flip-move#11]
In the readme you have:

> In the meantime, you should be able to easily add enter/exit transitions with ReactCSSTransitionGroup. I haven't personally tested it, but the two should play very nicely together, allowing you to combine custom enter/exit animations with Flip Move.

I tried doing this and ran into some issues. With code roughly like:

```jsx
<ReactCSSTransitionGroup component={FlipMove} typeName="div" className="row" transitionName="example" transitionEnterTimeout={500} transitionLeaveTimeout={300}>
  {...}
</ReactCSSTransitionGroup>
```

I get `Uncaught (in promise) TypeError: Cannot read property 'componentWillAppear' of undefined` in Chrome.

The other issue is that when removing FlipMove from the mix (and just using ReactCSSTransitionGroup) I noticed that the transition group will keep the leaving elements in the DOM until the animation has completed. I believe this would cause issues for FlipMove since it won't be able to know where the remaining elements will be transitioning to until the after the leave animation. Obviously I wasn't able to actually test this though.

In any case, great library, was able to drop it in and have it work without issue and I thought you might like some feedback on the ReactCSSTransitionGroup stuff.

**Comment by joshwcomeau** [comment]
Yeah, in retrospect it was a mistake to suggest something completely untested in the README.

Really good point about items not leaving the DOM until their transition has completed; hadn't realized that but yes, it stands to reason that the remaining items won't start to squeeze in until after the transition ends.

I've received a couple requests to add built-in onEnter/onExit animations, so it's the next new feature on the roadmap (after some perf stuff). Hoping to have time this weekend, but if not it shouldn't take more than a couple weeks :)

**Comment by BrianWalters** [comment]
Love this lib. Has saved me so much time already. What is your plan for adding Enter/Leave animations? Or any strategies we can use in the meantime?

You can sometimes add a css animation on the elements being FlipMove'd, which works well for a "enter" transition. I haven't figured out a good way to do exit animations, since the element is gone the moment React knows it should be gone.

**Comment by aight8** [comment]
Hey! Any plans for this functionality?

**Comment by aight8** [comment]
What about positioning a copy of the leaving element as absolute position relative to the container, then apply to it the leave animation. The leaved element must not removed to the dom in the current render cycle since at the end of the animation is must be invisible. This "leaveing" element must be appended in the render method to the "real" current childrens. It's another way like react's ReactCSSTransitionGroup but it do it job very well too, it's just another use case.

**Comment by joshwcomeau** [comment]
The method you suggest is what's used by [React Magic Move](https://github.com/ryanflorence/react-magic-move), and it's anathema to me; It introduces the overhead and performance cost of duplicating every DOM node that is being transitioned, and it would complicate the source code SO much. I believe it would introduce a ton of side effects as well; if the node has an `id`, you'd then have multiple "unique" items on the page. I believe refs would be confused as well.

I have an idea for how to do this properly, I just don't have the time to implement it.

I'm going to open a new issue to discuss the issue; too much back-story in this one :)
