### ISSUE TITLE
infinite scroll problem

### ISSUE THREAD

**Issue by alirezavalizade** [joshwcomeau/react-flip-move#114]
I use  react-flip-move component for animating to my lists, and have infinite scroll for them...this way have some issues. i want know react-flip-move dont support the infinite scrolling ?!
how to fix this?

**Comment by joshwcomeau** [comment]
Hi @alirezavalizade,

So, without more information/code/reproducible sample, I really can't even speculate what the problem is about. If your infinite scrolling isn't virtualized, it should work like anything else (after all, you're just appending new stuff to the DOM). If you are using some sort of virtualization, I've never tested that with FlipMove, so I'm not sure.

If you can share code or, ideally, a jsbin that replicates the issue, I'll be happy to take a look and see if I can spot the issue :)

**Comment by alirezavalizade** [comment]
yeah sure, I just have simple infinite scroll when user scroll to bottom of page i `setState()` to data but i think problem is with `staggerDurationBy` : 

```
<FlipMove
                staggerDurationBy={100}
                enterAnimation={ANIMATIONS.LIST}
              >
                {this.state.data ? this.state.data.map((item, index) =>
                  <ClientsItem
                    data={item}
                    key={index}
                  />
                ) : null}
</FlipMove>
```

**Comment by joshwcomeau** [comment]
Your issue is that you're using the `index` as the key. When the list gets shuffled, FlipMove doesn't think anything's changed, since index 0 is still in position 0, index 1 is still in position 1, etc.

**Comment by alirezavalizade** [comment]
i changed that to `item.uid` that is a unique iD but my problem not fixed ! 
problem is when i scroll down ,the elements render again and animation is very slow

**Comment by joshwcomeau** [comment]
Sounds like wrapping your <FlipMove> instances in components that use `ShouldComponentUpdate` to prevent unnecessary renders could help? Although that shouldn't really be necessary.

To be honest I can't even begin to debug something like that without a reproduction in jsbin.
