### ISSUE TITLE
Unexpected results with disableAllAnimations

### ISSUE THREAD

**Issue by willemx** [joshwcomeau/react-flip-move#115]
When rendering an array of items with `disableAllAnimations={false}` and then rerendering the list with a different array of items and `disableAllAnimations={true}` the old items are not removed (as I would expect) but stay onscreen, interspaced with the new array.
Is this as intended, or is it a bug?

**Comment by joshwcomeau** [comment]
That does sound like a bug; `disableAllAnimations` should basically turn `<FlipMove>` into a `<div>` (or whatever parent element you've wrapped its children in).

Unfortunately I'm a little backlogged now, I don't really foresee having time to tackle this issue :(

Apologies, hope you can find a workaround in the meantime!

Would happily accept contributions towards fixing this issue.

**Comment by willemx** [comment]
As a quick workaround, in the function `ComponentWillReceiveProps` in `react-flip-move.js`, I replaced `newChildren = this.isAnimationDisabled() ? ...` with `newChildren = nextProps.disableAllAnimations ? ...` 
This seems to fix my current problem, but I'm not sure if this is the complete solution.

**Comment by joshwcomeau** [comment]
@willemx Oh, I think I know what's going on. `isAnimationDisabled()` is a simple check that looks to see if `disableAllAnimations` is true, with a small optimization where it also checks if it can skip animations.

The issue is that it uses `this.props` instead of `nextProps`.

If you'd like credit for finding the issue, I'd happily accept a PR. Just pass `nextProps` to `isAnimationDisabled` and use it instead. You can check that it works using Storybook. 

Otherwise, I'm happy to tackle it myself. If all goes well I should be able to get a patch release published this evening.

Thanks for looking into it!

**Comment by joshwcomeau** [comment]
Ah I lied! Slipped my mind last night.

Will tackle it shortly. Setting a reminder this time!

**Comment by joshwcomeau** [comment]
Fix is published in `v2.7.3`
