### ISSUE TITLE
Allow order of animation to be passed

### ISSUE THREAD

**Issue by jackhopner** [joshwcomeau/react-flip-move#124]
In the scenario where I have:

```
<FlipMove
  staggerDurationBy="80"
  duration={600}
  enterAnimation={enterPresets.fade}
  leaveAnimation={leavePresets.fade}
  easing="linear"
  maintainContainerHeight={true}
>
  elements.map((e) => <span>e</span>)
</FlipMove>
```

However I want to add a collapse button and animate from the bottom upwards, therefore it would be useful if I could pass a prop to choose the animation order when either leaving or entering e.g

```
<FlipMove
  staggerDurationBy="80"
  duration={600}
  enterAnimation={enterPresets.fade}
  leaveAnimation={leavePresets.fade}
  enterOrder="forward"
  leaveOrder="reverse"
  easing="linear"
  maintainContainerHeight={true}
>
  elements.map((e) => <span>e</span>)
</FlipMove>
```

**Comment by joshwcomeau** [comment]
Hey @jackhopner,

So yeah, I can see the need for it, but it also seems like a very specific use-case. The implementation would be complex, I think (what happens if 2 items leave, 2 items enter, and 3 items just get shuffled around?). IMO this seems like the kind of niche that is best implemented via fork, rather than integrated into the original package.

I'll leave the issue open and see if it garners attention from others who need this feature, on the chance that I'm wrong and this is a common concern.

Thanks for the suggestion!

**Comment by joshwcomeau** [comment]
So yeah, sounds like this isn't too common of a situation. Going to close this issue, as I don't plan on adding this functionality any time soon.

Sorry, and best of luck!

**Comment by Guuz** [comment]
I ran into the same "issue".
I have a 2 column grid of 6 items:
```
x x
x x
x x
```
The grid always has 6 items, when you delete 1, another one is added at the bottom.
Using `staggerDelayBy` has a very beautiful effect! but only when removing 1 item. all subsequent items are moved 1-by-1 and a new item is added at the bottom.
When undoing this action though... the item at the bottom is removed first, but after that FlipMove starts at the top and adds/move items from there. Very ugly!
