### ISSUE TITLE
Double render of component

### ISSUE THREAD

**Issue by dfunaki** [joshwcomeau/react-flip-move#126]
Hi,  I have been trying to figure out why I am getting a double render of my component 
              
```
<FlipMove enterAnimation="fade" leaveAnimation="fade" typeName="div" >
       <Card
       key={item.id}
         item={item} />
</FlipMove>
```

If I put a console.log in the render method of my Card component,  I find that FlipMove renders the item twice?  I am running into an issue where the Card items that are being rendered are getting mixed up with what was rendered previously.  Has anyone else run into this issue?  Is there a way I can stop this?

**Comment by joshwcomeau** [comment]
Hey @dfunaki,

So, I created a simple demo here that does what you describe: https://jsbin.com/taziyifixe/1/edit?js,console,output

In that case, when the items are shuffled, their render methods are invoked twice. This is because we use a `transitionend` callback to do some cleanup once the animation is completed.

It shouldn't be causing problems though, unless you're adding and removing items very quickly, which is a [known issue](https://github.com/joshwcomeau/react-flip-move/issues/120).

If you can modify that jsbin to show the problem you're describing, I can see if I can find the problem.

**Comment by joshwcomeau** [comment]
Closing this as I haven't heard back. Feel free to follow up.

**Comment by dfunaki** [comment]
Hi Joshua,

  I am sorry I haven't been able to follow up just yet.  Things have been a
little busy.  When I have a chance I will reopen this

-Dan
