### ISSUE TITLE
No enter animation on first render

### ISSUE THREAD

**Issue by deibeljc** [joshwcomeau/react-flip-move#129]
One thing that bothers me is that I have to set my components list state on componentDidMount in order to get the enter animation to trigger. Is this the expected behavior? If so, how hard would it be to change it to play the enter animation on first render?

**Comment by joshwcomeau** [comment]
Right, so this is the expected behaviour - Similar to React CSSTransitionGroup, there's a distinction between `enter` and `appear`. The only difference is we never implemented `appear`, lol.

If you or anyone would like to create a PR for it, I think it's worth having :) It would be a new prop, `appearAnimation`, that would function like `enterAnimation` and `leaveAnimation`, but would only trigger on initial mount.

In terms of implementation... I'm not certain off the top of my head what the best way to do it would be. I'd look at ReactCSSTransitionGroup and see how they tackled it.

**Comment by deibeljc** [comment]
I'm on it! @joshwcomeau

**Comment by deibeljc** [comment]
So should the API be that you can define your own appearAnimation or should it just use the enterAnimation? I have a basic version working right now but it is using the enterAnimation values for the animation.

**Comment by deibeljc** [comment]
See [PR 130](https://github.com/joshwcomeau/react-flip-move/pull/130) for the code changes 😄

**Comment by joshwcomeau** [comment]
Merged! Released under `v2.9.0`

Thanks @deibeljc!
