### ISSUE TITLE
Transition property gets overwritten

### ISSUE THREAD

**Issue by lumio** [joshwcomeau/react-flip-move#136]
I am trying to animate a box-shadow on each element when appearing.
This is not possible, since transition is being overridden.

**Comment by joshwcomeau** [comment]
Indeed! This is listed in the [known issues](https://github.com/joshwcomeau/react-flip-move#known-issues). It's a hard one to fix.

An easy workaround is to just nest your items in a div:

```js
<FlipMove>
  <YourComponent>
    <div className="thing-with-box-shadow">
      ...
    </div>
  </YourComponent>
</FlipMove
```

**Comment by lumio** [comment]
What do you think of using some sort of replace-mechanism, that checks if a transition is in place, and if so flags it or clones it to be replaced later on?

As for your solution: Sounds fine to me!
Thank you

**Comment by joshwcomeau** [comment]
Ah, so I sorta-misunderstood your issue last night! My bad.

The hard issue to fix is when you want competing `transforms` (eg. `scale`). Wanting a custom `transition` isn't something I've thought much about. 

Yeah, so your suggestion makes sense; we can read the initial value from the node on mount, and revert to that after all transitions have completed. I'm hesitant to implement it, though, because it feels like a fair bit of additional complexity. This project is already surprisingly complex for what it does, and I'm on a mission to avoid complicating it further unless absolutely necessary.
