### ISSUE TITLE
How to highlight the recent changes?

### ISSUE THREAD

**Issue by frol** [joshwcomeau/react-flip-move#137]
Could you please give any tip on how to highlight the recent reorderings? I am implementing a ranking table, and I would love to highlight with background color the line which moved up (or down).

The move up/down animation works fine, but it would be even nicer if I improve the readability even further by adding green background to the items that moved up and red background to those which moved down: https://www.youtube.com/watch?v=BxtizpMB7P8

I have tried to use `onStart`/`onStartAll`/`onFinish`, but they don't provide any information about reordering, so I cannot make a decision on which items moved up or down.

**Comment by joshwcomeau** [comment]
Hey @frol, 

Hmm.

If a simple shuffle is happening, it's easy enough; I can check the array index of the item before and after the change, and assign an 'ascending'/'descending' prop.

But, what if an item is added into the middle of the list?

```diff
-[ 'a', 'b', 'c', 'd' ]
+[ 'a', 'b', 'e', 'c', 'd' ]
```

In this case, `'e'` isn't really ascending or descending, it's entering. Also, `'c'` and `'d'` are both descending, which I suppose makes sense... would you want to treat them such?

My biggest issue with this feature is trying to find an API that behaves as one would expect, lol. I'm not sure what should happen to adjacent items when something enters/leaves. Additionally I'm not sure what the best approach is... maybe I should convert `entering` and `leaving` to a `flip-move-status` prop, and add the possibilities of `ascending` and `descending`... That seems nicest to me, but it could also have consequences for users relying on those props... 

I'm fairly busy right now (just started a new job, and spare time is being spent on preparing a conf talk), but if you or anyone wanted to take a stab at this, I like the idea of adding this functionality :) otherwise it's not likely to attract much of my attention until mid-May at the earliest.

**Comment by frol** [comment]
> Also, 'c' and 'd' are both descending, which I suppose makes sense... would you want to treat them such?

Yes, this makes sense and it is fine for me.

> I'm fairly busy right now (just started a new job, and spare time is being spent on preparing a conf talk)

Sure, no problem. I didn't expect any solution right away, nevertheless, I thought it is worth to express the need rather to just silently wait for a miracle :)

I have actually hacked around this issue by watching the ascending/descending and setting the classes manually.

**Comment by joshwcomeau** [comment]
Gonna close this issue, feel free to re-open if anyone would like to discuss further!
