### ISSUE TITLE
React 15.5 PropType deprecation warnings

### ISSUE THREAD

**Issue by astanciu** [joshwcomeau/react-flip-move#138]

**Comment by joshwcomeau** [comment]
Hmm.

So, the solution to this problem is to use the `prop-types` package instead of importing them from `react`.

The `prop-types` package is only compatible with React 15 and the just-penned release of 0.14.9.

Lamely, I think this would need to be a major version bump, to avoid breaking things for users who use 0.14.8 and earlier. Which is annoying, since likely another major version bump will be required when React 16 comes out.

I think the simplest thing is just to allow the deprecation warnings for now. When React 16 comes out, Flip Move 3 will come out and will include this change. The deprecation warnings should only happen in dev, so it's not user-facing.

If anyone disagrees with this approach (or sees a better way), happy to discuss!

**Comment by atabel** [comment]
@joshwcomeau I think it doesn't need a major version bump because it will only break in development (React doesn't check proptypes in production builds). And the developer will be linked to http://fb.me/use-check-prop-types doc.
Other libs have done the change without releasing a major version:
https://github.com/bvaughn/react-virtualized/commit/5ef244538fdcf47fda8529d659f9001b81aafc16

**Comment by joshwcomeau** [comment]
Ah, thanks for the info @atabel 

Actually, now that I think about it, I think I'd rather just replace prop-types entirely with Flow. Going to open an issue and hopefully tackle that within the next week or two.
