### ISSUE TITLE
Fade out removed elements

### ISSUE THREAD

**Issue by flux627** [joshwcomeau/react-flip-move#16]
I'm not sure if this should be the responsibility of FlipMove, but it would be a nice touch. Any advice on where I should be looking to learn how to implement this would be helpful.

**Comment by joshwcomeau** [comment]
Yeah, sadly onExit animations turned out to be much more trouble than anticipated. It's something I'd like to add in at some point, but I don't have the time at the moment.

A so-so solution is you can do them sequentially; first fade out the element(s) that are about to be removed, and then re-arrange the existing animations. With a short fade, this actually looks pretty neat, but of course it depends on your circumstance.

The way you'd do this depends on your setup, but essentially you'd break it into two steps:

1) Do the fade itself. You can use a @keyframe animation, or simply apply styles like `opacity: 0; transition: 500ms`.

2) After the animation has completed, remove the now-invisible elements from the DOM. Flip Move will re-arrange them to fill the gaps.

Hope it helps! Sorry about not having a simpler solution.
