### ISSUE TITLE
Can't disable enter/leave animation

### ISSUE THREAD

**Issue by iamjager** [joshwcomeau/react-flip-move#171]
Hey, @joshwcomeau! First of all, thanks for a job well done — your component was exactly what I was looking for. However, it seems that I'm not able to disable enter/leave animations the way it is described in docs.

Here's my render function:
```
render() {
    const { items } = this.state;
    const {
      duration,
      easing
    } = this.props;

    return (
      <FlipMove
        duration={duration}
        easing={easing}
        enterAnimation={false}
        leaveAnimation={false}
      >
        {items.map(this.renderItem)}
      </FlipMove>
    );
  }
```
As you can see, I'm passing `false` to both `enterAnimation` and `leaveAnimation` — however, I'm still seeing a kind of animation when an item is added to/removed from a list. An item itself isn't being animated (it just appears/disappears immediately), but its "neighbours" are still being moved up or down with a transition. Is there anything I'm doing wrong or is this a bug? Thanks in advance!

**Comment by joshwcomeau** [comment]
Hey @iamjager, sorry for the delay!

So yeah, this is working as intended; the booleans simply disable the animation on the _item_ entering or leaving, but all the others are still subject to the typical "FlipMove" behaviour.

Now that you mention it, it does seem a little pointless to disable leave animations if the siblings will still shuffle around (well, unless you're adding/removing from the bottom of the list).

Thinking it through, it would be quite tricky to implement the behaviour it sounds like you want (we could disable the entire cycle when an enter or leave is detected, but what if items re-arrange themselves in that same update cycle?).

I think the hacky workaround in your situation would be to use `disableAllAnimations`, since this does what you'd expect. You'd have to work out when to update the boolean you pass to it, though (maybe through having some state, updated in `componentWillReceiveProps`, which works out whether to disable animations for this update or not?)
