### ISSUE TITLE
Children animation when top component leave

### ISSUE THREAD

**Issue by ioRekz** [joshwcomeau/react-flip-move#173]
Hello,

I'm working on a tool to make that kind of animation. On the clip, we can see the appearAnimation : using fade animation and delay from react flip move it's easy to reproduce. 
There are also animated list that makes use of childDelay so this library works very nice for this use case.

On problem is that usually, the leaveAnimations for the whole container and its children are the reverse as the entry. Inner components will fade out / slide out and then the main container will leave.

I would like to apply the same logic as my appear animations that is :
I only render the top container component so all the children will have their own appear animation + delay

When leaving I would like to only hide (not render) the top component but have the children first make their leaveTransition. 
The problem is that I have no control over it so the top container will leave before the children had time to trigger their leaveAnimation

**Comment by joshwcomeau** [comment]
Hm, I'm having a hard time understanding the exact issue... Can you share some code? The JSX for the setup you have, with comments explaining which element(s) you want to hide instead of remove, should help me understand.

**Comment by ioRekz** [comment]
Just discovered about codesandbox so here is an example.
I would like to produce the reverse animations when hiding that is :
The 2nd line fade out, then the first, then the container.
https://codesandbox.io/s/BBqmg4nZn

**Comment by joshwcomeau** [comment]
Ah, sorry for the huge delay! Didn't see this follow-up.

So yeah, I see what you mean; There's no declarative way to do this within FlipMove itself, since FlipMove doesn't know anything about nested instances. I think you could use `onFinishAll` to do what you want, though:

```
state = {
  showParent: true,
  showChildren: true
}

handleHideParent = () => {
  if (!this.showChildren) {
    this.setState({ showParent: false })
  }
}

render() {
  {showParent && (
    <FlipMove>
      {showChildren && (
        <FlipMove onFinishAll={this.handleHideParent />
      )}
    </FlipMove>
  )}
}
```

Essentially when the child finishes animating, you check to see if this was an 'exit' animation, and if so, you set the state to hide the parent, which animates the parent away.

To be honest I'm not certain that this will work. A more rudimentary approach might be needed, using a setTimeout:

```
state = {
  showParent: true,
  showChildren: true
}

onHide() {
  this.setState({ showChildren: false }, () => {
    window.setTimeout(() => (
      this.setState({ showParent: false }), this.props.animationDuration)
    ));
  });
}
```

Hope this helps! Sorry again about the huge delay :(

**Comment by ioRekz** [comment]
No problem for the delay, I'll try those approches, thanks !
