### ISSUE TITLE
Doesn't work w/ React 16 due to PropTypes

### ISSUE THREAD

**Issue by iEchoic** [joshwcomeau/react-flip-move#189]
See: https://github.com/joshwcomeau/react-flip-move/issues/138

This is now causing react-flip-move to break with React 16.

**Comment by Hypnosphi** [comment]
Which version of `react-flip-move` do you use?

**Comment by joshwcomeau** [comment]
@iEchoic I don't believe Flip Move uses PropTypes anymore! We moved to Flow a little bit ago.

I've been using it with React 16 as well, and it's worked perfectly for me (although I do need to update peer deps).

Gonna close the issue, since it's been a day since @Hypnosphi's response and I don't want folks to think it doesn't work. Please do follow up if upgrading to the latest version of Flip Move doesn't fix the issue though!
