### ISSUE TITLE
Automatically disable animations of nested FlipMove components while a parent is animating.

### ISSUE THREAD

**Issue by nbostrom** [joshwcomeau/react-flip-move#29]
Nested FlipMove components can lead to weird animations.

We could automatically disable animations of child FlipMove components while a parent is animating to prevent this.

I could probably fix this for my app in user land using `context`, `onStart`, `onFinish` and `disableAnimations`, but if you want this feature in core I could take a stab at it.

**Comment by joshwcomeau** [comment]
Hmm. A month or two ago, this came up; nested FlipMove animations were glitchy and weird, and it's because we were judging position relative to the viewport, instead of relative to the parent container.

I'll play with this in a bit and see for myself what the weirdness is, this time. My reflex is that it's probably an uncommon-enough use case to not be worth complicating the codebase for (making parent and child FlipMoves aware of each other sounds very tricky indeed)... And really, I would want them to both be able to animate simultaneously, rather than disabling child animations altogether.

**Comment by nbostrom** [comment]
Yeah, really sorry about this. I should really update the lib before posting issues. Everything seems to work fine now. Thanks for your hard work on this and for looking into my totally unnecessary issue ;)

**Comment by joshwcomeau** [comment]
No problem! Happy to hear it :)
