### ISSUE TITLE
Add issue for bug referenced in example

### ISSUE THREAD

**Issue by hasPatrickC** [joshwcomeau/react-flip-move#35]
Hi,

Can you be more specific about which bug this refers to?

https://github.com/joshwcomeau/react-flip-move/blob/gh-pages/examples/components/1_Shuffle.jsx#L168

A) I'd love to try to help fix this.

and

B) I'd like to know what to look for when implementing a temporary workaround.

**Comment by joshwcomeau** [comment]
Hi Patrick!

Yeah, good catch. I meant to do that, and totally forgot. I don't have the time right now to post a proper issue summary, but I'll look into this later today and open a proper issue for it!

**Comment by hasPatrickC** [comment]
No rush, thanks for the quick reply!

**Comment by joshwcomeau** [comment]
Hey @hasPatrickC,

Ok! I fixed the problem. Gonna write it up, in case anyone finds it interesting.

I have an `onFinishAll` handler that fires when all animations have completed. The way I know about this is with a counter; when an item needs to be animated, I increment it. When the item finishes animating, I decrement it.

Once all items have finished animating, I need to do some cleanup, by removing any items from the DOM that were busy transitioning away (when the component receives new props and an item is missing, I can't just render the new props, because then the item would instantly disappear; instead, I transfer it to state, transition it away, and then remove it from the DOM when it's invisible). 

The problem is this: when the `onFinishAll` handler involves a re-render of the parent component (via `setState`, for example), the FlipMove component receives new props. This can be _before_ the FlipMove has finished with its cleanup, since it invokes the `onFinishAll` callback synchronously, the cleanup is async, and `setState` on the parent component wins. Dammit, Javascript.

Understanding all this took me quite a bit, but once I did, the solution was obvious: Don't invoke the `onFinishAll` handler until after the cleanup is completed, in the `setState` callback.

There is a bit of a bigger issue under the surface, and that's why the update caused problems. For today, though, I'm just happy to have solved the immediate problem.

@hasPatrickC, really appreciate the offer to help :) If you'd like to contribute to this project, feel free to dig into this problem a little deeper and see if you can find a more elegant solution

**Comment by joshwcomeau** [comment]
Also, one small thing I noticed when troubleshooting is that the counter is actually completely unnecessary. I keep an array of elements that need to be animated, and could just as easily use its length as the counter, instead of a dedicated variable. Maybe, by checking uniqueness, we could solve this problem as well?

**Comment by hasPatrickC** [comment]
Wow, thank you for the detailed writeup. I'll try to make some time to poke around and see if there's anything I can help with. Getting react-flip-move up and running was super simple so thanks for open sourcing this!!
