### ISSUE TITLE
Doesn't animate parent size on add/remove

### ISSUE THREAD

**Issue by matthewoates** [joshwcomeau/react-flip-move#40]
Hey Josh,

Really like the project. I'm using the `FlipMove` component inside of an isolated div, and then there are components before and after that div. The containing div's size changes without animation when you add and remove elements. I think the example here http://joshwcomeau.github.io/react-flip-move/examples/#/shuffle?_k=inhhwi gets around this by cheating a little. You'll see that the +/- buttons have the same parent as the list elements.

If you set the background of the `div` that contains the `li`s and the `footer` to something obscene like red you'll see what I'm talking about.

I can include an animation if this is confusing.

Is there a way to get the parent div size to animate smoothly?

**Comment by matthewoates** [comment]
Derp. "Is there a way to get the parent div size to animate smoothly?" Of course there is. Another CSS animation.

I got around this by precalculating the height of the `FlipMove` component and then attaching a `transition: 'height 1s`. Would be nice if this was supported natively by the library, but I'm not sure how to get around the hardcoding of the height.

**Comment by joshwcomeau** [comment]
Yeah no I see what you mean. I am indeed cheating in the demo, although to me it just made sense; if I want something to do the Flip animation, it should be wrapped by FlipMove :)

The children don't have to all be the same size/shape; you can probably do this too, by just wrapping everything. It may require a restructuring of your code, since all children need to be shallowly rendered (not inside containing <div>s).

Otherwise, this _could_ be handled at the library level; I could calculate the size of the box in its initial and final state, and transition between the two. It would be tricky to do this with `transform` though, and I don't want to have any non-accelerated CSS properties in the library.

I can also envision lots of weird edge-case problems with this solution. 

Sadly, I think this is something that should be tackled by the developer on a case-by-case basis.

Thanks for using the library!

**Comment by jamby** [comment]
@matthewoates Was wondering how exactly you fixed this? I'm still trying to fix it but I'm lost on how you decided to do it?

Thanks!

**Comment by matthewoates** [comment]
Hey @jamby 

I explained this in my earlier comment:

I got around this by precalculating the height of the FlipMove component and then attaching a transition: 'height 1s. Would be nice if this was supported natively by the library, but I'm not sure how to get around the hardcoding of the height.

To elaborate/reiterate, you'll want to create a wrapper element where you compute the height yourself and add a transition on the height attribute.
