### ISSUE TITLE
FlipMove does not take CSS scale() into account.

### ISSUE THREAD

**Issue by Guuz** [joshwcomeau/react-flip-move#55]
Hello,

If FlipMove is used inside an element that is scaled the animation start positions are not correctly calculated. An easy example of this is to run this code on this page and use the demo functions:
http://joshwcomeau.github.io/react-flip-move/examples/#/shuffle
```js
$$('#main-content')[0].style.transform = 'scale(0.5)';
```

I've tracked the problem down to `getPositionDelta()`. This should fix it on the vertical axis:
```js
return [oldBox.left - relativeBox.left, oldBox.top / SCALE_FACTOR - relativeBox.top / SCALE_FACTOR];
```

I admit the use case is probably not very big. Our application is scaled to maintain the same aspect ratio and element positions on every screen. But there are other use cases to use `scale()`.

I don't see any other way to get the correct values when using CSS scaling. This is how `getBoundingClientRect()` works. Do you see any other way?
**Would it be an option to introduce a prop for for the scale factor?** It should default to `1` of course.

I also tried extending the component to overwrite the `getPositionDelta()`. But because a `PropConverter` is used extending is "broken". When you extend FlipMove you are actually extending PropConverter so you can't access any of FlipMove's internals. Any thoughts on this?

Thanks in advance!

**Comment by joshwcomeau** [comment]
Hi @Guuz!

Yeah, you're not the first to point out that the PropConverter HOC gets in the way. I never really envisioned anyone extending the FlipMove class, and I see problems with the idea; for one thing, I don't have the discipline to guarantee consistency with internal methods. A patch version could break the extension.

That said, I'd probably be really frustrated in your shoes, since you have a not-unreasonable use-case and FlipMove isn't making it easy for you. Sorry about that!

I wonder if there's a way to do it programmatically; Climb up the node tree checking for transform props, and applying any you find to an overall multiplier. It'd be hard to make it dynamic (I guess it could be done on mount, and on update?), and I don't know how performant it'd be with large DOM trees... Animations would also be a problem (if the scale is animated on load, we'd read the mid-transition value without being aware that it'd about to go away).

If you have any thoughts on how to refine this idea, I'd be super interested in it. Could even be its own NPM package, to help any project deal with `getBoundingClientRect` inside scaled nodes.

For adding the prop, I'd like to wait and see if it becomes a more common issue. I'm trying to avoid implementing fixes for rare issues if it comes at the cost of a more complex API (there's already so many more properties than I had originally wanted). 

My advice would be to fork it and implement it in your copy; the downside with that is it's a pain to update to newer versions, but I don't see FlipMove getting any fancy new features or anything, it's mostly about optimizations and fixes from here out. If you aren't having any other problems with it, I'd say go for it :)

**Comment by Guuz** [comment]
Thanks for the quick response!

I'd rather extend FlipMove then forking it. When I extend it it is much more declarative what I have done in my codebase. You don't have to guarantee internal consistency because with extending and overwriting functions comes a risk you should be willing to take. But it's less maintenance than forking. We can fix the version in NPM and just run an update and check our code of it's still working.
And the smaller the function you extend the better. Maybe just have a wrapper for `getBoundingClientRect` so i can divide it by the scale factor there. That code won't ever break.

I understand you don't just want to add any prop. Seeing how FlipMove works (by using `getBoundingClientRect`) it does kinda make sense though, to have that prop. Else it can never work in a scaled container. Also the complexity of the prop is fairly low. It's just a division as i showed in my code example.

If you're really sure extending won't be made possible and a prop won't be introduced any time soon I respect your decisions on this. It's your module ;-) These are all the ideas I have to make it work though. So worst case I will fork it and make some changes.

Thanks again!

**Comment by joshwcomeau** [comment]
Yeah, fair point about extending v. forking. 

Maybe I could add a prop like `positionCalculator`, a function that defaults to `getBoundingClientRect` but can be overwritten with any function that takes a DOM node as an argument and returns an object with position and size. I like this solution more than a simple `scale` prop because it's much more flexible, and could be used in a bunch of specialized cases.

I have a pretty busy week, but if this solution works for you I should be able to have it up by Friday. You can also submit a PR if you'd like :)

Let me know! Thanks

**Comment by Guuz** [comment]
That's a very good solution! All the pieces were there but you found a way to combine them :-)

I'm also quite busy but I would like to give it a go. Hopefully this week! We'll keep in touch. 

Thanks!

**Comment by Guuz** [comment]
I gave it a go and I think I got it working as you described. I'll work on the rough edges and will submit a PR soon.

**Comment by joshwcomeau** [comment]
:rocket:
