### ISSUE TITLE
unable to use FlipMove inside child component 

### ISSUE THREAD

**Issue by AnuragSinghTomarr** [joshwcomeau/react-flip-move#58]
I have a parent app component named as App inside that i am passing the child component as this.props.children.  Let say we have the child component as List, her i am unable to use <FlipMove></FlipMove> as it does not show any effect. I have used a boilerplate for mine project link - https://github.com/erikras/react-redux-universal-hot-example. here is mine files https://gist.github.com/AnuragSinghTomarr/b728cb07ea571097fca18e2e4815bc03

Please let me know the issue

**Comment by joshwcomeau** [comment]
Hi!

I _believe_ the issue is that your `<li>` needs to have a `display` property of `inline-block` or `block`. Very hard to move around inline elements, and `<li>`s default to `inline`.

Please reopen if that doesn't solve the problem :) Also, if it doesn't, can you put the files in a proper repo? I'll clone it and poke around.

Thanks!

**Comment by AnuragSinghTomarr** [comment]
i have updated the code instead of ul and li tag now i am simply using  a div tag in mine home.js file here is the link https://gist.github.com/AnuragSinghTomarr/b728cb07ea571097fca18e2e4815bc03 , than also animations are not working
