### ISSUE TITLE
issue reference to #58 issue

### ISSUE THREAD

**Issue by AnuragSinghTomarr** [joshwcomeau/react-flip-move#61]
i have updated the code instead of ul and li tag now i am simply using a div tag in mine home.js file here is the link https://gist.github.com/AnuragSinghTomarr/b728cb07ea571097fca18e2e4815bc03 , than also animations are not working

**Comment by joshwcomeau** [comment]
Hi @AnuragSinghTomarr,

Weird, I don't see anything wrong with that code. Are you getting any error messages? Is the issue that when `this.props.popular` changes, the items just instantly appear in their new position? Is it both enter/leave animations *and* shuffling that isn't working, or just one of them?

Sorry for the delay, been a busy week!

**Comment by AnuragSinghTomarr** [comment]
hi @joshwcomeau

enter/leave animations and shuffling none of them are working

**Comment by joshwcomeau** [comment]
Very weird. The code related to FlipMove is very simple and looks correct, but there's a fair bit of additional logic that may be affecting it somehow. 

I think in order to help diagnose and fix the problem, I need either:

* a link to the full repo, so I can run it locally and poke around, or
* a jsbin that replicates the issue

A quicker solution would be to try [React Shuffle](https://github.com/FormidableLabs/react-shuffle). It doesn't use hardware-accelerated CSS properties, but otherwise it achieves much the same effect, and it may work for you!

**Comment by joshwcomeau** [comment]
Going to close this, because I haven't been able to replicate it.
