### ISSUE TITLE
Example of onStart function

### ISSUE THREAD

**Issue by GilbertMizrahi** [joshwcomeau/react-flip-move#62]
Great library. 
This is not an issue. Can you write an example of how a onStart function would look like.

I want to animate the list items (flex items) when they first appear. Similar to transitionAppear on react-addons-css-transition-group. I am using React Flip Move to animate when adding/removing items and it works great, but I want to also animate onStart.

**Comment by joshwcomeau** [comment]
Sorry for the delay! Just saw this.

It sounds like what you're describing is `enterAnimation`; When items first appear, the `enterAnimation` is applied. There are presets, but you can also specify an object of `from` / `to` CSS properties, similarly to how ReactCSSTransitionGroup works :)

To be honest, `onStart` is one of those properties that I added because I received a few requests for it, for various edge-case purposes. You shouldn't need to use it for simple purposes; I personally haven't needed to use it. 

Examples I've seen:

- Unrelated trigger. Eg. open a popup when a specific list item is animated.
- Additional transition CSS. Eg. make the background red while the item is animated.

Hope it helps!
