### ISSUE TITLE
Changing width does not animate

### ISSUE THREAD

**Issue by meepeek** [joshwcomeau/react-flip-move#65]
As in example http://joshwcomeau.github.io/react-flip-move/examples/#/shuffle?_k=8t0vgp

Clicking Grid button then click List button, list items are moved, however no animation for the width expanding or shrinking.

PS. could you share the concept of how you control the animation ?

**Comment by joshwcomeau** [comment]
That's true; this package specifically handles reordering, not changes in size.

The reason is that certain CSS properties are efficient, and others are not. Animating `width` or `height` will not look pretty. I use `transform: translate` for all the rearranging.

It's theoretically possible in some circumstances to use `transform: scale` to enlarge or resize, but the problem is it treats the entire container as a texture. Any text in the container would be stretched as if it was a single image, so it would not look good. It works fine for simple shapes, but that's rarely what people need to animate.

The concept is explained in detail in this blog post: https://medium.com/developers-writing/animating-the-unanimatable-1346a5aab3cd
