### ISSUE TITLE
this.props.children is an opaque object

### ISSUE THREAD

**Issue by jsg2021** [joshwcomeau/react-flip-move#66]
I just read through the code and noticed children being accessed as if it's always an array. Which is not true. If you have one child, it is often not an array.

The 'children' should be accessed through [React.Children.*](https://facebook.github.io/react/docs/top-level-api.html#react.children) methods to be safe. :)

**Comment by joshwcomeau** [comment]
I have a HOC that does this, along with a bunch of other gross-but-necessary prop-converting things :) 

https://github.com/joshwcomeau/react-flip-move/blob/master/src/prop-converter.js#L42

I did it this way because I wanted to keep the main component straightforward, and deal with the clutter elsewhere. Since props are immutable, a HOC was the way to pseudo-mutate props.

In retrospect, it may be adding more confusion than it solves, though. I think a better way to organize it is to have the component handle all React-y things, and delegate to different modules (one for DOM manipulation, one for position calculation, etc).

But yes, rest assured that you're free to pass single children in!

**Comment by jsg2021** [comment]
awesome :) thanks
