### ISSUE TITLE
Bundle JS

### ISSUE THREAD

**Issue by BeerBelly** [joshwcomeau/react-flip-move#72]
Hi,

I'm trying to make a bundled JS using Babelify and Browserify with the presets es2015, es2016 and react but getting an error. Can you help with what is needed?

**Comment by joshwcomeau** [comment]
I'm afraid I know very little about browserify, I've been using Webpack for quite some time...

If you can share the error(s) you're getting I'm happy to take a look, but it sounds like your problem may not be with Flip Move itself.

**Comment by BeerBelly** [comment]
If I use the es2016 preset I get this error:

`SyntaxError: node_modules/react-flip-move/src/FlipMove.js: Unexpected token (29:0)
  27 |
  28 |
> 29 | @propConverter
     | ^
  30 | class FlipMove extends Component {
  31 |   constructor(props) {
  32 |     super(props);
    at Parser.pp.raise `

es2015 gives me this error:
`ReferenceError: [BABEL] node_modules\react-flip-move\src\FlipMove.js: Unknown option: foreign.Children.`

Thank you for taking a look though

**Comment by joshwcomeau** [comment]
Right; so the issue is I use decorators, which aren't a part of ES2015 or ES2016 (they're stage 4, I believe, so they should make it into Javascript by 2017).

Thankfully, though, you shouldnt have to use the `/src` files. I ship a `/lib` directory with NPM that includes the transpiled code, so you shouldn't need babel at all.

In fact, the lib file is the primary export. If you `import FlipMove from 'react-flip-move'` or `require 'react-flip-move'`, you should get the transpiled version...

Can you share more information about how you're importing the file?

**Comment by BeerBelly** [comment]
I tried bundling the lib version and it went through without errors:
`browserify node_modules/react-flip-move/lib/FlipMove.js -o bundle.js -t [ babelify --presets [ es2016 react ] ]`

I then included the bundle.js file normally in my HTML file `<script src="js/bundle.js"></script>`
but when I tried to make a list it still didn't see the FlipMove class...I didn't import since in my understanding the bundle should have all the data needed without the import?

embedded:166 Uncaught ReferenceError: FlipMove is not defined is the error I get when I use the script tag only...

**Comment by BeerBelly** [comment]
Looks like I had an issue with my Browserify config...started in a fresh directory with freshly installed addons I needed and now it works...sorry for the confusion.
