### ISSUE TITLE
Invariant Violation

### ISSUE THREAD

**Issue by onomatopoetry** [joshwcomeau/react-flip-move#75]
Hi Josh,
FlipMove looks awesome, it's exactly what I need! I'm trying to put together a scoreboard for a site that runs wine events. Here's the relevant functions from my Scoreboard component:

```
render() {
	return <FlipMove>
			{this._renderScoreboardItems()};
		</FlipMove>
},
_renderScoreboardItems() {
	var scoreboard = this.state.scoreboard;
	return scoreboard.map(function(scoreboardItem, index) {
		return <li className="scoreboard-item" key={scoreboardItem.retailerName + scoreboardItem.wineName}>
			<span className="rating-rank">{index + 1}.</span>
			<span className="rating-stars">
				{[1, 2, 3, 4, 5].map(function(star) {
					var starType;
					if(star <= scoreboardItem.rating) {
						starType = "star";
					} else {
						starType = scoreboardItem.rating + 0.5 >= star ? "star-half-full" : "star-o";
					}
					return <FontAwesome name={starType} key={star}/>
				})} ({scoreboardItem.numRatings} ratings)
			</span>
			<span className="rating-description">{ scoreboardItem.wineName + " from " + scoreboardItem.retailerName }</span>
		</li>
	});
},
```

When transpile + run this, I'm getting a warning and an error:
First: _Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `FlipMove`. See https://fb.me/react-warning-keys for more information._ This is puzzling me - I do have unique keys for the members of FlipMove

And then: _Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined._

If I replace the opening and closing tags for `<FlipMove>` with `<ul>`s, The errors do not appear, and the page runs fine. I'm pretty stumped on this one! Are there any mandatory config variables I'm missing? Have you seen this before? I can't tell if I've found a bug or the limits of my own puny intelligence. What do you think?

**Comment by joshwcomeau** [comment]
Huh. Everything looks pretty alright to me!

My best guess would be that one or more items in `this.state.scoreboard` has an issue. A few thoughts:

- Are there any times where either `scoreboardItem.retailerName` or `scoreboardItem.wineName` can be undefined? 
- What happens when you remove all the ratings stuff (rank, stars, description)? Does it work if you simplify it to just an `<li>` with a "hello world" string inside?
- What happens when you replace `var scoreboard = this.state.scoreboard` with a simplified version of your state, with only the fields needed for the render method?

Also: by default, FlipMove uses a `<div>`, but you can specify a different element with `typeName`. I'd use `<FlipMove typeName="ul">`. I doubt it'll fix your problem, but it's always good to be compliant with the spec.

If none of the above fixes your issue, it's entirely possible you've found a bug with FlipMove; If you can create a jsbin/codepen/whatever that replicates the issue, I'll be happy to poke around and see if I can fix the problem :)

**Comment by onomatopoetry** [comment]
Sometimes, as a programmer, you uncover something truly mysterious. You work for days, you learn and you learn, you curse Alan Turing, and you finally realize in a moment of sublime catharsis that you've solved one of the hardest puzzles you've come across. You've done it, you're a real engineer. And sometimes, it's a fucking semicolon.

It was this little bastard: `{this._renderScoreboardItems()};` in `render()`;

I'll never put a semicolon in JSX ever again as long as I live, but this was a terrible way to find out how it can fail. Sorry for wasting your time my friend, I look forward to using your creation!

**Comment by joshwcomeau** [comment]
Hahahaha. No worries :) glad it's working now
