### ISSUE TITLE
Footer shoots up during removal

### ISSUE THREAD

**Issue by jamby** [joshwcomeau/react-flip-move#78]
So I have this portion of code:

```javascript
<div className="list">
  <FlipMove
    staggerDelayBy={30}
    duration={500}
    enterAnimation="fade"
    leaveAnimation="fade"
    onStart={this.animationStart}
    onFinish={this.animationFinish}
  >
    {items.map(this.renderItem)}
    <Footer />
  </FlipMove>
</div>
```

And what happens, is that when I remove an Item, the Footer component decides to move up immediately before the animation finishes (so it appears under the current list of items, and then when it's finally removed it's already there).

Is there something I'm missing to fix this?

**Comment by joshwcomeau** [comment]
Hey @jamby,

I believe the issue is that you're missing a `key` prop on the `<Footer />`. Otherwise it should absolutely work :)

If the problem persists, I'm happy to poke around and troubleshoot if you can get a reproduction of the issue on jsbin or similar.

**Comment by jamby** [comment]
So I figured out why it was breaking. I had `col-xs-12` (floats) around all the items before, and not around the footer, so the footer was part of the whole "list", which is why it wasn't moving properly.

However, it does make me wonder about problem that arised: When things get removed, if I have an actual footer on the web page (with a scrollable webpage unlike your demo), what seems to happen is the footer for the web page shoots up too quickly. So the footer on my React stuff seem to be moving fluidly (along with the footer inside the React that was the problem originally) but it overlaps the website footer that has already been moved up.

I'm attempting to add an animation on the area surrounding the React stuff, but not going well so far.

**Comment by joshwcomeau** [comment]
Yeah, so one thing Flip Move _doesn't_ handle is animating the parent container's height. The reason is simply that you can't use hardware acceleration, so the animation would be choppy.

This has been covered in https://github.com/joshwcomeau/react-flip-move/issues/40.

There are a few potential solutions:

- You can structure your page so that all items are siblings in the <FlipMove> wrapper. This sounds really messy on non-trivial apps, though.
- You can give the parent container a `min-height`, so that content won't jump up to fill the gap
- You can handle the animation yourself, with CSS animations. This is the approach the user in that other issue went with. I tend to frown on this because it can be janky, but it's kinda the best solution if you need that transition to animate.

I have had the idea that this could be sorta-solved in the library by wrapping the entire app in a wrapper, and using special props to indicate that items should be FlipMove'd. There are a bunch of complications with this idea though, so it isn't likely to happen anytime soon.

Let me know if you run into any other issues!
