### ISSUE TITLE
Delay container resize on element removal

### ISSUE THREAD

**Issue by rhys-vdw** [joshwcomeau/react-flip-move#80]
Hi @joshwcomeau. Firstly, I'm loving this library! Basically achieved everything I was looking for as a simple drop-in replacement for `ul`. No configuration required.

One problem I'm experiencing is that elements are being removed from the dom flow before they animate away:

![flipmove-container-jump](https://cloud.githubusercontent.com/assets/822105/19140254/fc6ca722-8bd6-11e6-8bc5-7481e305abb0.gif)

In one view we have a list with very large elements. When removing them the entire document beneath will jump up underneath the element as it animates away. Other similar libraries I've seen do this hold the space open until the element disappears and then snap to the new size. I think this is preferred behaviour.

So - is there already an option for this behaviour? If not, would you like me to provide a PR to address this? If you have any tips for how to make this change that would be good. Otherwise I'm pretty confident that I can navigate your (immaculately commented 👍) codebase.

**Comment by joshwcomeau** [comment]
Hi @rhys-vdw!

That's a good point; I've received a few requests to animate container size, which is a very hairy (and really kind of impossible to do at 60fps) problem. But simply holding the container size while the elements shift and _then_ shortening it would be a good compromise-solution.

If you can provide a PR that would be great! Some prop like `maintainContainerSize`.

If you haven't already, I'd recommend reading [my blog post](https://medium.com/developers-writing/animating-the-unanimatable-1346a5aab3cd#.o6zcmuws8) about this library, to get a general sense of how it works.

After that, to point you in the right direction, here's how I think the problem ought to be solved:

- We're already storing the parent's bounding box. This is good, because it should have the `height` property already. Accessible through `this.parentBox.height`.

- On [this line](https://github.com/joshwcomeau/react-flip-move/blob/master/src/FlipMove.js#L195), we're recomputing the parentBox at a very specific moment in time: After the layout has been recalculated (so the new height is set), but before those changes have been painted to the screen. So we need to capture the original height before that line, saved to something like `const originalParentHeight = this.parentBox.height`.

- If the new height is less than the former height, apply a style to the parent node (`this.parentElement`) locking in the current height.

- Inside [finishTriggerHooks](https://github.com/joshwcomeau/react-flip-move/blob/master/src/FlipMove.js#L445), we need to undo that change, by unsetting the height.

This is pretty straightforward, but like with everything, there are a few things that make it more complex:

- the `boundingBox` takes padding and border into account, but if the user hasn't set `box-sizing: border-box`, when _we_ set the height to be equal to the bounding box's height, it may artificially inflate it. Solution could just be to apply box-sizing to the element, but that may mess with the user's current layout. The more arduous but safer approach is to check what the box-sizing is set to, and if it isn't border-box, subtract the padding and border heights from the boundingBox's height.

- Interruptions may be messy:

    - The list shrinks, so we artificially apply a height of 100px even though the height is about to become 75px.
    - Before our `triggerFinishHooks` method has run, the user adds two new items, so the height grows to 125px
    - Because we've applied a strict `height` in the style, the new bounding box is calculated to still be `100px`, not `125px`.
    - The height remains fixed at the original 100px until all animations have completed, even if content overlaps the stuff below.

    One easy solution could be to use `min-height` instead of `height`?
    The flip-side is that if the list continues to shrink, we actually _want_ to preserve the initial height until all animations are complete, so that actually works well :)

Those are the issues I can see ahead of time, but you may encounter others. This library deals with deceptively complex issues.

For contributions, we do have tests. They're tricky, since I have yet to find a clean way to test time-sensitive DOM stuff like this, but if you can add one just testing the base case, that'd be great. For all other edge cases and tricky situations, we can use [react storybook](https://github.com/kadirahq/react-storybook) to ensure everything works.

Finally, if the DOM manipulation gets complex (eg. the stuff with calculating padding/border for `box-sizing: content-box`), please put it in its own little module. I've wanted to move the other DOM side-effect stuff out of the component for a while, so this may be a good place to start.

Thanks for your interest, let me know if I can assist :)

**Comment by rhys-vdw** [comment]
Hi @joshwcomeau. Thanks for the detailed response. I'm getting started on this now.

**Comment by rhys-vdw** [comment]
Hey @joshwcomeau. So I read through your blog post and guide here and this all seems quite reasonable. But before I did this thought I'd try [this alternative strategy](https://github.com/usabilityhub/react-flip-move/commit/457ddf90cba7439170d758288be6f551a9101972) that doesn't require applying styles to the container at all. When there are any elements disappearing, a placeholder is added to the end of the list to maintain their height (as if they hadn't been removed from the flow by `position: absolute`).

I think this sidesteps the interruption concerns you had, since the placeholder height is calculated from `state` at `render()` time.

Also am I right in thinking this avoids the `box-sizing` issue by creating a placeholder div without any `padding` or `border` size?

Perhaps you'll see some problems with this approach, but it just seemed more immediately achievable for me. If this is not appropriate I'm happy to go back to your approach. Otherwise I'll clean this up and introduce the `maintainContainerSize` prop, test case etc.

**Comment by joshwcomeau** [comment]
That's super clever!

I like this approach, it's much more elegant than what I had proposed.

The issue with summing the heights of the children is that margin isn't accounted for, and I don't know how it works if things are positioned artificially with `top`/`bottom`. It solves the box-sizing issue, but there's still this stuff.

I think we could just read the height of the parent container, though? Capture the original height on initial/earlier renders, re-capture the height when items are added/removed, get the diff of the two heights, create an item that maintains that height. 

I do have a slight concern about performance if the actions are happening quickly, but I think we can mitigate it by being a bit smart; in the case of an interrupt, we'd check for the existence of a placeholder and update its height, instead of destroying/recreating it.

But yeah, your commit is on the right track :) I like this strategy.

**Comment by rhys-vdw** [comment]
> I like this approach

Great. :-)

> Capture the original height on initial/earlier renders, re-capture the height when items are added/removed

Yep. Sounds like that would work.

> I do have a slight concern about performance if the actions are happening quickly, but I think we can mitigate it by being a bit smart; in the case of an interrupt, we'd check for the existence of a placeholder and update its height, instead of destroying/recreating it.

Currently the placeholder [maintains the same key](https://github.com/usabilityhub/react-flip-move/commit/457ddf90cba7439170d758288be6f551a9101972#diff-173d41f486956cae79d23564b18cf1e0R499). React will, as you described, update the existing element's height in place when it flushes any updates to the DOM.

> But yeah, your commit is on the right track :)

I'm going to try to throw together a complete PR for you.
