### ISSUE TITLE
Support functional components

### ISSUE THREAD

**Issue by geelen** [joshwcomeau/react-flip-move#95]
See #94. Not sure if anything _should_ prevent stateless functional components from working, but then again I don't understand the dark wizardry inside this library so maybe there's something I'm missing 😄

**Comment by joshwcomeau** [comment]
The issue is refs; For FlipMove to do its magic, it needs to reach down into the children you provide it:

```js
// Not actual code, but roughly representative

this.props.children.map(child => (
  React.cloneElement(
    child, 
    { ref: (element) => this.childrenRefs.push(element) }
  )
);
```

While you can use refs _inside_ functional components, the components themselves don't support refs.

There is a potential workaround that has been [discussed](https://github.com/joshwcomeau/react-flip-move/issues/89) - Essentially we'd pass down a 'ref' function, and the developer would have to use that prop as the component's ref.

It's a complex solution that requires devs to remember to do this odd thing, though, so I'm more a fan of advocating that users just wrap their SFCs in a <div> or something.

**Comment by geelen** [comment]
Oh right from the other issue the solution is to wrap all your SFCs in a `<div>`? (I'm assuming that's what you meant to type above...)
